# Generated by Django 4.0.6 on 2022-07-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pv',
            field=models.IntegerField(auto_created=True, default=None, verbose_name='浏览量'),
        ),
    ]
